### ISSUE TITLE
Bullseye attack code not working

### ISSUE THREAD

**Issue by sunan93** [JonasGeiping/poisoning-gradient-matching#2]
Hi, I have been getting the following error when I tried to run the Bullseye attack code:-
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [64, 3, 3, 3], but got 2-dimensional input of size [500, 3072] instead
Command used to run the code : python brew_poison.py --recipe bullseye
This is because the last_layer of the model didn't expect this input size (reference file : forest/witchcoven/witch_bullseye.py). I tried a few changes to the code, but it didn't work out. 
Could you kindly share the latest working code for the bullseye attack?

**Comment by JonasGeiping** [comment]
Hi, thanks for reporting this issue.
I can't reproduce the error with my setup. Could you share more info about your pytorch & OS version?
Also, does the error also appear in dryrun mode (python brew_poison.py --recipe bullseye --dryrun)?

In any case, a likely culprit is the bypass_last_layer function in witch_bullseye.py. This function has the underlying assumption that

` new_model = torch.nn.Sequential(*list(model.children())) `

can construct a `new_model` that is identical to `model`. If that works, then constructing the feature-space representation `torch.nn.Sequential(*(layer_cake[:-1]), torch.nn.Flatten())` should also work.

**Comment by sunan93** [comment]
Hi, yes the error also appears when I ran in dryrun mode. 
And my OS is ubuntu 16.04 LTS. My torch version is 1.8.1 on python 3.8.
Thanks.

**Comment by JonasGeiping** [comment]
Ok I can replicate your problem on one machine. Are you using a machine with multiple GPUs? 

I can replicate the error on a machine with several GPUs. torch.nn.DataParallel breaks the abovementioned assumption in that case. If you need multiple GPUs, I would check if the model is an instance of DataParallel and then rebuild the DataParallel structure via something like
```
        layer_cake = list(model.module.children())
        last_layer = layer_cake[-1]
        headless_model = torch.nn.DataParallel(torch.nn.Sequential(*(layer_cake[:-1]), torch.nn.Flatten()))
```
or directly send model.module to the _Witch object, running the poisoning part on a single GPU.


Historically, we implemented multi-GPU functionality in the code, but usually ended up rather running N separate experiments instead of 1 experiment with N GPUs, given that we want to have at least 10 experiments for any reported number, due to the variance in poisoning success for random targets.

**Comment by sunan93** [comment]
Yes I am using two GPUs currently.

**Comment by sunan93** [comment]
Thanks, the code changes worked. Hence, I am closing the thread.

**Comment by jhuvehicle** [comment]
I am getting the same error with the following command:

from datetime import datetime
startTime = datetime.now()
!python brew_poison.py --dataset MNIST

print(datetime.now() - startTime)

**Comment by jhuvehicle** [comment]
urrently evaluating -------------------------------:
Tuesday, 13. February 2024 05:32PM
Namespace(net=['ResNet18'], dataset='MNIST', recipe='gradient-matching', threatmodel='single-class', poisonkey=None, modelkey=None, deterministic=False, eps=16, budget=0.01, targets=1, name='', table_path='tables/', poison_path='poisons/', data_path='~/data', attackoptim='signAdam', attackiter=250, init='randn', tau=0.1, scheduling=True, target_criterion='cross-entropy', restarts=8, pbatch=512, pshuffle=False, paugment=True, data_aug='default', full_data=False, adversarial=0, ensemble=1, stagger=False, step=False, max_epoch=None, ablation=1.0, loss='similarity', centreg=0, normreg=0, repel=0, nadapt=2, clean_grad=False, vruns=1, vnet=None, retrain_from_init=False, pretrained=False, optimization='conservative', epochs=None, noaugment=False, gradient_noise=None, gradient_clip=None, lmdb_path=None, cache_dataset=False, benchmark='', benchmark_idx=0, dryrun=False, save=None, local_rank=None)
CPUs: 4, GPUs: 1 on 00feb0659aed.
GPU : Tesla T4
ResNet18 model initialized with random key 519305415.
Downloading http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz
Downloading http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz to /root/data/MNIST/raw/train-images-idx3-ubyte.gz
100% 9912422/9912422 [00:00<00:00, 82502130.72it/s]
Extracting /root/data/MNIST/raw/train-images-idx3-ubyte.gz to /root/data/MNIST/raw

Downloading http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz
Downloading http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz to /root/data/MNIST/raw/train-labels-idx1-ubyte.gz
100% 28881/28881 [00:00<00:00, 172312509.00it/s]
Extracting /root/data/MNIST/raw/train-labels-idx1-ubyte.gz to /root/data/MNIST/raw

Downloading http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz
Downloading http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz to /root/data/MNIST/raw/t10k-images-idx3-ubyte.gz
100% 1648877/1648877 [00:00<00:00, 21313111.03it/s]
Extracting /root/data/MNIST/raw/t10k-images-idx3-ubyte.gz to /root/data/MNIST/raw

Downloading http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz
Downloading http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz to /root/data/MNIST/raw/t10k-labels-idx1-ubyte.gz
100% 4542/4542 [00:00<00:00, 36355970.93it/s]
Extracting /root/data/MNIST/raw/t10k-labels-idx1-ubyte.gz to /root/data/MNIST/raw

Data mean is (0.13066373765468597,), 
Data std  is (0.30810782313346863,).
Data is loaded with 4 workers.
Initializing Poison data (chosen images, examples, targets, labels) with random seed 1299090130
Poisoning setup generated for threat model single-class and budget of 1.0% - 600 images:
--Target images drawn from class 3 - three with ids [7252].
--Target images assigned intended class 2 - two.
--Poison images drawn from class 2 - two.
Starting clean training ...
Traceback (most recent call last):
  File "/content/poisoning-gradient-matching/brew_poison.py", line 32, in <module>
    stats_clean = model.train(data, max_epoch=args.max_epoch)
  File "/content/poisoning-gradient-matching/forest/victims/victim_base.py", line 85, in train
    return self._iterate(kettle, poison_delta=None, max_epoch=max_epoch)
  File "/content/poisoning-gradient-matching/forest/victims/victim_single.py", line 54, in _iterate
    self._step(kettle, poison_delta, loss_fn, self.epoch, stats, *single_setup)
  File "/content/poisoning-gradient-matching/forest/victims/victim_base.py", line 128, in _step
    run_step(kettle, poison_delta, loss_fn, epoch, stats, model, defs, criterion, optimizer, scheduler)
  File "/content/poisoning-gradient-matching/forest/victims/training.py", line 103, in run_step
    outputs = model(inputs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torchvision/models/resnet.py", line 285, in forward
    return self._forward_impl(x)
  File "/content/poisoning-gradient-matching/forest/victims/models.py", line 297, in _forward_impl
    x = self.conv1(x)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [64, 3, 3, 3], expected input[128, 1, 28, 28] to have 3 channels, but got 1 channels instead
0:00:09.540191

**Comment by jhuvehicle** [comment]
@JonasGeiping @lhfowl

**Comment by jhuvehicle** [comment]
@JonasGeiping  this is the issue where I should of put the comments. What changes do I need to make to the code if I am only using one GPU?
