### ISSUE TITLE
Where is poison frogs?

### ISSUE THREAD

**Issue by wesbz** [JonasGeiping/poisoning-gradient-matching#3]
Hi, I've been trying to investigate your code and can't seem to find where did you implemented the Poison Frogs algorithm?
Thanks in advance.

**Comment by JonasGeiping** [comment]
You can use --recipe poison-frogs to use the poison frogs objective. (Although to be entirely exact, you would want the version from https://github.com/JonasGeiping/data-poisoning/blob/main/forest/witchcoven/witch_poison_frogs.py)

**Comment by wesbz** [comment]
Thanks for your response, but as I saw the file you linked here, I do not see poison frogs' algorithm. Where is the backward step?

**Comment by JonasGeiping** [comment]
Do you mean where the objective is optimized?

This happens in https://github.com/JonasGeiping/poisoning-gradient-matching/blob/68ecd823e378b1ac436ce5449ad1cf0d0cbc2ec4/forest/witchcoven/witch_base.py#L194

**Comment by wesbz** [comment]
Thanks for helping, I wasn't clear, I guess 😅
<img width="608" alt="image" src="https://user-images.githubusercontent.com/5843554/178787543-57ee96e2-337c-46e7-a129-1a3f0601d1ce.png">
I'm missing something as I do not find this in your code 😟
Thanks in advance

**Comment by JonasGeiping** [comment]
Ah I see what you are looking for. The backward step in algorithm 1 can actually be understood as a "backward" projection onto the second objective in the original poison-frogs formulation. The second objective penalizes deviations from the base image b in an l^2 norm. 

In this repo we only look at poisons that are penalized to lie in a small l^infty ball around b. To us, this made it simpler to compare to adversarial evasion attacks which also use this constraint. Both constraints are equally valid though and attacks can generally be optimized to fulfill either constraint.

The equivalent projection onto the l^infty ball is then found here: https://github.com/JonasGeiping/poisoning-gradient-matching/blob/68ecd823e378b1ac436ce5449ad1cf0d0cbc2ec4/forest/witchcoven/witch_base.py#L268
If you wanted to optimize the attack within an l^2 norm constraint, you would want to modify those lines.

**Comment by JonasGeiping** [comment]
Closing this for now. Let me know if you have more questions!
