### ISSUE TITLE
Runtime error in witch_base.py

### ISSUE THREAD

**Issue by umang4002** [JonasGeiping/poisoning-gradient-matching#4]
![image](https://github.com/JonasGeiping/poisoning-gradient-matching/assets/111570202/1bcd5cfe-ca98-4602-8bd0-c33e090235f2)

I used the command !python brew_poison.py--net ConvNet --eps 8 --budget 0.001 --dataset MNIST --recipe gradient-matching

**Comment by umang4002** [comment]
While running the witch_base.py on collab on T4 GPU the function _.batched_step() is not working properly.

**Comment by JonasGeiping** [comment]
I'd guess that your pytorch version is too new, and `.grad` is deleted during `zero_grad`. You can try changing the `zero_grad` invocation [here](https://github.com/JonasGeiping/poisoning-gradient-matching/blob/68ecd823e378b1ac436ce5449ad1cf0d0cbc2ec4/forest/witchcoven/witch_base.py#L167C37-L167C37) to `zero_grad(set_to_none=False)`

**Comment by umang4002** [comment]
Thankyou @JonasGeiping it worked.

**Comment by JonasGeiping** [comment]
I' m glad

**Comment by jhuvehicle** [comment]
I am able to run the brew using this command but when I use the default parameters I am not:

Currently evaluating -------------------------------:
Saturday, 10. February 2024 06:52PM
Namespace(net=['ResNet18'], dataset='MNIST', recipe='gradient-matching', threatmodel='single-class', poisonkey=None, modelkey=None, deterministic=False, eps=16, budget=0.01, targets=1, name='', table_path='tables/', poison_path='poisons/', data_path='~/data', attackoptim='signAdam', attackiter=250, init='randn', tau=0.1, scheduling=True, target_criterion='cross-entropy', restarts=8, pbatch=512, pshuffle=False, paugment=True, data_aug='default', full_data=False, adversarial=0, ensemble=1, stagger=False, step=False, max_epoch=None, ablation=1.0, loss='similarity', centreg=0, normreg=0, repel=0, nadapt=2, clean_grad=False, vruns=1, vnet=None, retrain_from_init=False, pretrained=False, optimization='conservative', epochs=None, noaugment=False, gradient_noise=None, gradient_clip=None, lmdb_path=None, cache_dataset=False, benchmark='', benchmark_idx=0, dryrun=False, save=None, local_rank=None)
CPUs: 4, GPUs: 1 on 902b0fdda028.
GPU : Tesla T4
ResNet18 model initialized with random key 1308584379.
Data mean is (0.13066373765468597,), 
Data std  is (0.30810782313346863,).
Data is loaded with 4 workers.
Initializing Poison data (chosen images, examples, targets, labels) with random seed 2580594265
Poisoning setup generated for threat model single-class and budget of 1.0% - 600 images:
--Target images drawn from class 2 - two with ids [9359].
--Target images assigned intended class 5 - five.
--Poison images drawn from class 5 - five.
Starting clean training ...
Traceback (most recent call last):
  File "/content/poisoning-gradient-matching/brew_poison.py", line 32, in <module>
    stats_clean = model.train(data, max_epoch=args.max_epoch)
  File "/content/poisoning-gradient-matching/forest/victims/victim_base.py", line 85, in train
    return self._iterate(kettle, poison_delta=None, max_epoch=max_epoch)
  File "/content/poisoning-gradient-matching/forest/victims/victim_single.py", line 54, in _iterate
    self._step(kettle, poison_delta, loss_fn, self.epoch, stats, *single_setup)
  File "/content/poisoning-gradient-matching/forest/victims/victim_base.py", line 128, in _step
    run_step(kettle, poison_delta, loss_fn, epoch, stats, model, defs, criterion, optimizer, scheduler)
  File "/content/poisoning-gradient-matching/forest/victims/training.py", line 103, in run_step
    outputs = model(inputs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torchvision/models/resnet.py", line 285, in forward
    return self._forward_impl(x)
  File "/content/poisoning-gradient-matching/forest/victims/models.py", line 297, in _forward_impl
    x = self.conv1(x)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [64, 3, 3, 3], expected input[128, 1, 28, 28] to have 3 channels, but got 1 channels instead
0:00:04.519582

**Comment by JonasGeiping** [comment]
Looks like a CIFAR model used with MNIST data

**Comment by jhuvehicle** [comment]
So certain models work with certain datasets?

**Comment by jhuvehicle** [comment]
Right now the default parameters are working in my colab environment. It may have been a bug.

**Comment by jhuvehicle** [comment]
urrently evaluating -------------------------------:
Tuesday, 13. February 2024 05:32PM
Namespace(net=['ResNet18'], dataset='MNIST', recipe='gradient-matching', threatmodel='single-class', poisonkey=None, modelkey=None, deterministic=False, eps=16, budget=0.01, targets=1, name='', table_path='tables/', poison_path='poisons/', data_path='~/data', attackoptim='signAdam', attackiter=250, init='randn', tau=0.1, scheduling=True, target_criterion='cross-entropy', restarts=8, pbatch=512, pshuffle=False, paugment=True, data_aug='default', full_data=False, adversarial=0, ensemble=1, stagger=False, step=False, max_epoch=None, ablation=1.0, loss='similarity', centreg=0, normreg=0, repel=0, nadapt=2, clean_grad=False, vruns=1, vnet=None, retrain_from_init=False, pretrained=False, optimization='conservative', epochs=None, noaugment=False, gradient_noise=None, gradient_clip=None, lmdb_path=None, cache_dataset=False, benchmark='', benchmark_idx=0, dryrun=False, save=None, local_rank=None)
CPUs: 4, GPUs: 1 on 00feb0659aed.
GPU : Tesla T4
ResNet18 model initialized with random key 519305415.
Downloading http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz
Downloading http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz to /root/data/MNIST/raw/train-images-idx3-ubyte.gz
100% 9912422/9912422 [00:00<00:00, 82502130.72it/s]
Extracting /root/data/MNIST/raw/train-images-idx3-ubyte.gz to /root/data/MNIST/raw

Downloading http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz
Downloading http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz to /root/data/MNIST/raw/train-labels-idx1-ubyte.gz
100% 28881/28881 [00:00<00:00, 172312509.00it/s]
Extracting /root/data/MNIST/raw/train-labels-idx1-ubyte.gz to /root/data/MNIST/raw

Downloading http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz
Downloading http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz to /root/data/MNIST/raw/t10k-images-idx3-ubyte.gz
100% 1648877/1648877 [00:00<00:00, 21313111.03it/s]
Extracting /root/data/MNIST/raw/t10k-images-idx3-ubyte.gz to /root/data/MNIST/raw

Downloading http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz
Downloading http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz to /root/data/MNIST/raw/t10k-labels-idx1-ubyte.gz
100% 4542/4542 [00:00<00:00, 36355970.93it/s]
Extracting /root/data/MNIST/raw/t10k-labels-idx1-ubyte.gz to /root/data/MNIST/raw

Data mean is (0.13066373765468597,), 
Data std  is (0.30810782313346863,).
Data is loaded with 4 workers.
Initializing Poison data (chosen images, examples, targets, labels) with random seed 1299090130
Poisoning setup generated for threat model single-class and budget of 1.0% - 600 images:
--Target images drawn from class 3 - three with ids [7252].
--Target images assigned intended class 2 - two.
--Poison images drawn from class 2 - two.
Starting clean training ...
Traceback (most recent call last):
  File "/content/poisoning-gradient-matching/brew_poison.py", line 32, in <module>
    stats_clean = model.train(data, max_epoch=args.max_epoch)
  File "/content/poisoning-gradient-matching/forest/victims/victim_base.py", line 85, in train
    return self._iterate(kettle, poison_delta=None, max_epoch=max_epoch)
  File "/content/poisoning-gradient-matching/forest/victims/victim_single.py", line 54, in _iterate
    self._step(kettle, poison_delta, loss_fn, self.epoch, stats, *single_setup)
  File "/content/poisoning-gradient-matching/forest/victims/victim_base.py", line 128, in _step
    run_step(kettle, poison_delta, loss_fn, epoch, stats, model, defs, criterion, optimizer, scheduler)
  File "/content/poisoning-gradient-matching/forest/victims/training.py", line 103, in run_step
    outputs = model(inputs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torchvision/models/resnet.py", line 285, in forward
    return self._forward_impl(x)
  File "/content/poisoning-gradient-matching/forest/victims/models.py", line 297, in _forward_impl
    x = self.conv1(x)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [64, 3, 3, 3], expected input[128, 1, 28, 28] to have 3 channels, but got 1 channels instead
0:00:09.540191

**Comment by JonasGeiping** [comment]
but you're running with a single GPU?

**Comment by jhuvehicle** [comment]
Yes a single GPU. T4 GPU google colab. I am not sure google colab allows for more than one GPU.

**Comment by jhuvehicle** [comment]
https://stackoverflow.com/questions/57999776/distributed-training-in-tensorflow-using-multiple-gpus-in-google-colab

**Comment by JonasGeiping** [comment]
Sorry, let me be more explicit. This here is an issue about an error occuring with the bullseye attack when using multiple GPUs. This does not seem to be your problem, your problem is different.

**Comment by jhuvehicle** [comment]
ok

**Comment by jhuvehicle** [comment]
I saw the error in another issue. These comments should not be here. close the ticket.
